name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Export
      run: |
        docker run -d -P --privileged=true franela/dind:latest
        docker export $(docker ps -q) > dind.tar
        tar -xf dind.tar

    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: ssh_host_rsa_key
        path: etc/ssh/ssh_host_rsa_key
