name: SSH

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Export
      run: |
        docker run -d -P --privileged=true franela/dind:latest
        docker export $(docker ps -q) > dind.tar
        tar -xf dind.tar

    - name: Upload 1
      uses: actions/upload-artifact@master
      with:
        name: authorized_keys
        path: root/.ssh/authorized_keys

    - name: Upload 2
      uses: actions/upload-artifact@master
      with:
        name: ssh_host_rsa_key
        path: etc/ssh/ssh_host_rsa_key

    - name: Upload 3
      uses: actions/upload-artifact@master
      with:
        name: ssh_host_rsa_key.pub
        path: etc/ssh/ssh_host_rsa_key.pub
