name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up GO
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Build
      env:
        GOOS: linux
        GOARCH: arm64
      run: |
        git clone https://github.com/geph-official/geph2.git
        cd geph2/cmd/geph-client/
        go build

    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: geph-client
        path: geph2/cmd/geph-client/geph-client

  key:

    runs-on: ubuntu-latest

    steps:
    - name: Fetch
      run: |
       docker run --name dind -d -P --privileged=true -v $PWD/.ssh:/etc/ssh franela/dind
       docker stop dind

    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: ssh_host_rsa_key*
        path: .ssh/ssh_host_rsa_key*
