name: Trojan

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - run: |
        brew install cmake boost openssl coreutils python
        wget -q https://dl.google.com/android/repository/android-ndk-r20b-darwin-x86_64.zip
        unzip -q android-ndk-r20b-darwin-x86_64.zip
        export OPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1
        export NDK=$PWD/android-ndk-r20b
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/darwin-x86_64
        export AR=$TOOLCHAIN/bin/aarch64-linux-android-ar
        export AS=$TOOLCHAIN/bin/aarch64-linux-android-as
        export CC=$TOOLCHAIN/bin/aarch64-linux-android29-clang
        export CXX=$TOOLCHAIN/bin/aarch64-linux-android29-clang++
        export LD=$TOOLCHAIN/bin/aarch64-linux-android-ld
        export RANLIB=$TOOLCHAIN/bin/aarch64-linux-android-ranlib
        export STRIP=$TOOLCHAIN/bin/aarch64-linux-android-strip
        git clone https://github.com/trojan-gfw/trojan.git $HOME/trojan
        cd $HOME/trojan
        mkdir build
        cd build/
        cmake -DENABLE_MYSQL=OFF -DBoost_USE_STATIC_LIBS=ON ..
        make -j4

    - uses: actions/upload-artifact@master
      with:
        name: trojan
        path: /Users/runner/trojan/build/trojan
