name: Trojan

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
        sudo add-apt-repository ppa:mhier/libboost-latest -y
        sudo apt-get update > /dev/null
        sudo apt-get -y -qq install build-essential cmake libboost libssl-dev default-libmysqlclient-dev > /dev/null
        wget -q https://dl.google.com/android/repository/android-ndk-r20b-linux-x86_64.zip
        unzip -q android-ndk-r20b-linux-x86_64.zip
        export NDK=$PWD/android-ndk-r20b
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export AR=$TOOLCHAIN/bin/aarch64-linux-android-ar
        export AS=$TOOLCHAIN/bin/aarch64-linux-android-as
        export CC=$TOOLCHAIN/bin/aarch64-linux-android29-clang
        export CXX=$TOOLCHAIN/bin/aarch64-linux-android29-clang++
        export LD=$TOOLCHAIN/bin/aarch64-linux-android-ld
        export RANLIB=$TOOLCHAIN/bin/aarch64-linux-android-ranlib
        export STRIP=$TOOLCHAIN/bin/aarch64-linux-android-strip
        git clone https://github.com/trojan-gfw/trojan.git $HOME/trojan
        cd $HOME/trojan
        mkdir build
        cd build/
        cmake ..

    - uses: actions/upload-artifact@master
      with:
        name: trojan
        path: /home/runner/trojan/build/trojan
