name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
        sudo apt -y install build-essential cmake libboost-all-dev libssl-dev default-libmysqlclient-dev
        wget  -q https://dl.google.com/android/repository/android-ndk-r20b-linux-x86_64.zip &> /dev/null
        unzip android-ndk-r20b-linux-x86_64.zip
        export CC=$PWD/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi19-clang
        export CXX=$PWD/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi19-clang++
        git clone https://github.com/trojan-gfw/trojan.git $HOME/trojan
        cd $HOME/trojan
        mkdir build
        cd build/
        cmake ..

    - uses: actions/upload-artifact@master
      with:
        name: trojan
        path: /home/runner/trojan/build/trojan
